name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
  intl: ^0.19.0
  http: ^0.13.3
  flutter_dotenv: ^5.0.2
  table_calendar: ^3.0.0
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^9.1.5
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.6
  timezone: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0


flutter:
  assets:
    - assets/loader.gif
    - assets/person.svg
    - assets/search_schedule.svg
    - assets/place_icon.svg
    - assets/group_icon.svg
    - assets/teacher_icon.svg
    - .env
    - assets/no_data.svg
    - assets/calendar.svg
    - assets/remotely.svg
    - assets/sun_icon.svg
    - assets/moon_black.svg
    - assets/moon_white.svg
    - assets/calendar_dark.svg
    - assets/settings.svg
    - assets/person_white.svg
    - assets/no_data_dark.svg
    - assets/search_schedule_dark.svg
    - assets/house.svg
    - assets/calendar_icon.svg
    - assets/bell.svg
    - assets/hand.svg
    - assets/rocket.svg
    - assets/rocket_white.svg
    - assets/search.svg
    - assets/clear.svg
    - assets/free_time_icon.svg
    - assets/KSRS.svg
    - assets/change.svg
    - assets/logo.svg
    - assets/KSRS_white.svg
    - assets/rest_day.svg
    - assets/rest_day_white.svg
    - assets/lecture_icon.svg
    - assets/book_icon.svg
    - assets/additional_icon.svg
    - assets/clock.svg
    - assets/no_internet.svg
    - assets/server_down.svg
    - assets/no_internet_dark.svg
    - assets/server_down_dark.svg
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Italic.ttf
          style: italic
 
  uses-material-design: true


